# Generated by Django 4.2.6 on 2023-11-01 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organization.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "org",
                    models.CharField(
                        default=organization.models.generate_pk,
                        editable=False,
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("postal_code", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField()),
                ("industry", models.CharField(max_length=255)),
                ("employee_count", models.PositiveIntegerField()),
                ("founding_date", models.DateField()),
                ("legal_entity_type", models.CharField(max_length=255)),
                ("tax_id_number", models.CharField(max_length=255)),
                ("registration_number", models.CharField(max_length=50)),
                ("registration_date", models.DateField()),
                ("logo", models.ImageField(blank=True, null=True, upload_to="image")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent",
                        to="organization.organization",
                    ),
                ),
                (
                    "subsidiaries",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subsidiaries",
                        to="organization.organization",
                    ),
                ),
            ],
        ),
    ]
