# Generated by Django 4.2.6 on 2023-11-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="subsidiaries",
            field=models.ManyToManyField(blank=True, to="organization.organization"),
        ),
    ]
