# Generated by Django 4.2.6 on 2023-11-01 09:46

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0003_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="dept",
            field=models.CharField(
                default=organization.models.generate_dept_pk,
                editable=False,
                max_length=255,
                unique=True,
            ),
        ),
    ]
