# Generated by Django 4.2.6 on 2023-11-01 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0004_department_dept"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="dept",
        ),
    ]
