# Generated by Django 4.2.6 on 2023-11-01 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0008_remove_team_department"),
        ("organization", "0005_remove_department_dept"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Department",
        ),
    ]
