# Generated by Django 4.2.6 on 2023-11-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0006_delete_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
