# Generated by Django 4.2.7 on 2023-12-05 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0019_taskpriority_badge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("db_events", "0007_alter_userauthenticationlog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklog",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log",
                to="tasks.task",
            ),
        ),
        migrations.AlterField(
            model_name="tasklog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
