# Generated by Django 4.2.7 on 2023-12-16 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flow", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Action",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="root",
        ),
        migrations.DeleteModel(
            name="State",
        ),
    ]
