# Generated by Django 4.2.7 on 2023-12-16 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flow", "0002_delete_action_remove_workflow_root_delete_state"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkFlow",
        ),
    ]
