# Generated by Django 4.2.8 on 2023-12-25 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("flow", "0007_alter_state_action_alter_state_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.group",
            ),
        ),
    ]
