# Generated by Django 4.2.4 on 2023-10-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="profile_image/default.jpeg", upload_to="profile_image"
            ),
        ),
    ]
