# Generated by Django 4.2.6 on 2023-11-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_member_of"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="profile_image/default.jpeg", upload_to="images"
            ),
        ),
    ]
