# Generated by Django 4.2.6 on 2023-11-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(default="images/default.jpeg", upload_to="images"),
        ),
    ]
