# Generated by Django 4.2.7 on 2023-11-19 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_user_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
    ]
