# Generated by Django 4.2.7 on 2023-11-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0012_remove_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="member_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member",
                to="auth.group",
            ),
        ),
    ]
