# Generated by Django 4.2.4 on 2023-10-25 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reminders", "0002_remove_reminder_assign_to_me"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="assign_to",
        ),
        migrations.AddField(
            model_name="reminder",
            name="assign_to",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
