# Generated by Django 4.2.7 on 2023-12-07 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reminders", "0003_remove_reminder_assign_to_reminder_assign_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="reminder",
        ),
    ]
