# Generated by Django 4.2.6 on 2023-11-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="tags",
            field=models.ManyToManyField(blank=True, to="mail.tag"),
        ),
    ]
