# Generated by Django 4.2.6 on 2023-11-04 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0002_alter_mail_tags"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mail",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
