# Generated by Django 4.2.6 on 2023-11-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="related_articles",
            field=models.ManyToManyField(blank=True, null=True, to="articles.article"),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, to="articles.articletags"
            ),
        ),
    ]
