# Generated by Django 4.2.6 on 2023-11-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_article_related_articles_alter_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="related_articles",
            field=models.ManyToManyField(blank=True, to="articles.article"),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(blank=True, to="articles.articletags"),
        ),
    ]
