# Generated by Django 4.2.6 on 2023-11-05 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_alter_articleapprovalstatus_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="attachments",
        ),
    ]
