# Generated by Django 4.2.6 on 2023-11-05 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0006_remove_article_attachments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="approval_status",
        ),
        migrations.RemoveField(
            model_name="article",
            name="importance",
        ),
        migrations.RemoveField(
            model_name="articletags",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="articletags",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="articletags",
            name="description",
        ),
        migrations.RemoveField(
            model_name="articletags",
            name="updated_at",
        ),
        migrations.DeleteModel(
            name="ArticleApprovalStatus",
        ),
    ]
