# Generated by Django 4.2.6 on 2023-11-06 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0009_sharearticle_commentsharearticle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentsharearticle",
            name="share_article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="articles.sharearticle",
            ),
        ),
    ]
