# Generated by Django 4.2.6 on 2023-11-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0011_sharearticle_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
