# Generated by Django 4.2.6 on 2023-11-08 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0015_alter_article_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="is_approved",
        ),
    ]
