# Generated by Django 4.2.6 on 2023-11-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0016_remove_article_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="approve_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
