# Generated by Django 4.2.6 on 2023-11-16 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0017_article_approve_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="art",
        ),
        migrations.CreateModel(
            name="PendingArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("approve_comment", models.TextField(blank=True, null=True)),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("HIGH", "HIGH"),
                            ("MEDIUM", "MEDIUM"),
                            ("LOW", "LOW"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "attachments",
                    models.FileField(blank=True, null=True, upload_to="attachments"),
                ),
                (
                    "approval_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articles.articleapprovalstatus",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_articles",
                    models.ManyToManyField(blank=True, to="articles.pendingarticle"),
                ),
                ("tags", models.ManyToManyField(blank=True, to="articles.articletags")),
            ],
        ),
    ]
