# Generated by Django 4.2.6 on 2023-11-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0018_remove_article_art_pendingarticle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingarticle",
            name="related_articles",
            field=models.ManyToManyField(blank=True, to="articles.article"),
        ),
    ]
