# Generated by Django 4.2.6 on 2023-10-29 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0003_remove_team_members"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktype",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="team.team",
            ),
        ),
    ]
