# Generated by Django 4.2.6 on 2023-10-29 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0002_tasktype_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assign_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Assigner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
