# Generated by Django 4.2.6 on 2023-11-10 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0004_taskassignmenthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskassignmenthistory",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tasks_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskassignmenthistory",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
