# Generated by Django 4.2.6 on 2023-11-12 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0008_taskpriorityhistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskPriorityHistory",
        ),
    ]
