# Generated by Django 4.2.6 on 2023-11-12 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0011_taskstatuschange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskstatuschange",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_log",
                to="tasks.task",
            ),
        ),
    ]
