# Generated by Django 4.2.6 on 2023-11-16 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0013_taskprioritychange"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskStatusChange",
        ),
    ]
