# Generated by Django 4.2.6 on 2023-11-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0016_delete_taskassignmenthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcomment",
            name="attachments",
            field=models.FileField(blank=True, null=True, upload_to="attachments"),
        ),
    ]
