# Generated by Django 4.2.7 on 2023-11-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0017_taskcomment_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcomment",
            name="attachment_title",
            field=models.CharField(
                blank=True, default="attachment", max_length=50, null=True
            ),
        ),
    ]
