# Generated by Django 4.2.7 on 2023-12-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0018_taskcomment_attachment_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskpriority",
            name="badge",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
