# Generated by Django 4.2.7 on 2023-12-07 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0020_task_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="task",
        ),
    ]
