# Generated by Django 4.2.8 on 2023-12-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flow", "0005_remove_state_action_state_action"),
        ("tasks", "0022_rename_creator_task_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasktype",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="tasktype",
            name="work_flow",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="flow.workflow",
            ),
        ),
    ]
