# Generated by Django 4.2.8 on 2023-12-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flow", "0006_alter_workflow_diagram"),
        ("tasks", "0023_remove_tasktype_assigned_to_tasktype_work_flow"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskLogFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_flow",
                        to="flow.workflow",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_state",
                        to="flow.state",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_task",
                        to="tasks.task",
                    ),
                ),
            ],
        ),
    ]
