# Generated by Django 4.2.8 on 2023-12-16 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0025_tasklogflow_attachments_1_tasklogflow_attachments_2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasklogflow",
            name="is_active",
        ),
    ]
