# Generated by Django 4.2.8 on 2023-12-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flow", "0006_alter_workflow_diagram"),
        ("tasks", "0027_task_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="actions",
            field=models.ManyToManyField(blank=True, to="flow.action"),
        ),
    ]
