# Generated by Django 4.2.8 on 2023-12-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flow", "0006_alter_workflow_diagram"),
        ("tasks", "0028_task_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklogflow",
            name="action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="flow.action",
            ),
        ),
    ]
