# Generated by Django 4.2.8 on 2023-12-16 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flow", "0006_alter_workflow_diagram"),
        ("tasks", "0029_tasklogflow_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklogflow",
            name="flow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flow_flow",
                to="flow.workflow",
            ),
        ),
        migrations.AlterField(
            model_name="tasklogflow",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flow_state",
                to="flow.state",
            ),
        ),
    ]
