# Generated by Django 4.2.8 on 2023-12-17 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0031_task_current_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="process_percentage",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
            preserve_default=False,
        ),
    ]
