# Generated by Django 4.2.6 on 2023-11-13 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="asset_type",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="assigned_user",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="status",
        ),
        migrations.DeleteModel(
            name="AsetStatus",
        ),
        migrations.DeleteModel(
            name="Asset",
        ),
        migrations.DeleteModel(
            name="AssetCondition",
        ),
        migrations.DeleteModel(
            name="AssetType",
        ),
    ]
