# Generated by Django 4.2.6 on 2023-11-16 13:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("asset", "0003_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AsetStatus",
            new_name="AssetStatus",
        ),
    ]
