# Generated by Django 4.2.6 on 2023-11-16 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("asset", "0005_rename_asset_name_asset_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="last_maintenance_date",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="purchase_date",
        ),
    ]
