# Generated by Django 4.2.6 on 2023-11-16 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("asset", "0006_remove_asset_last_maintenance_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="warranty_expiry_date",
        ),
    ]
