# Generated by Django 4.2.7 on 2023-11-25 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("asset", "0007_remove_asset_warranty_expiry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="condition",
        ),
        migrations.DeleteModel(
            name="AssetCondition",
        ),
    ]
