# Generated by Django 4.2.7 on 2023-11-25 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("asset", "0009_asset_byod_asset_image_asset_imei_asset_supplier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_key", models.CharField(max_length=100)),
                ("software_name", models.CharField(max_length=100)),
                ("product_key", models.CharField(max_length=100)),
                ("seats", models.IntegerField()),
                ("company", models.CharField(max_length=100)),
                ("manufacturer", models.CharField(max_length=100)),
                ("licensed_to_name", models.CharField(max_length=100)),
                ("licensed_to_email", models.EmailField(max_length=254)),
                ("reassignable", models.BooleanField(default=False)),
                ("supplier", models.CharField(max_length=100)),
                ("order_number", models.CharField(max_length=100)),
                ("purchase_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("purchase_date", models.DateField()),
                ("expiration_date", models.DateField()),
                ("termination_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_order_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("depreciation", models.DecimalField(decimal_places=2, max_digits=10)),
                ("maintained", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="asset.licensecategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
