# Generated by Django 4.2.7 on 2023-12-09 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("asset", "0013_consumablecategory_consumable"),
    ]

    operations = [
        migrations.RenameField(
            model_name="license",
            old_name="category_name",
            new_name="category",
        ),
    ]
