# Generated by Django 4.2.7 on 2023-12-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asset", "0014_rename_category_name_license_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetstatus",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="assettype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
