# Generated by Django 4.2.6 on 2023-11-01 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0006_delete_department"),
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="department",
                to="organization.organization",
            ),
        ),
    ]
