# Generated by Django 4.2.6 on 2023-11-01 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0003_department_created_at_department_created_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="org",
            new_name="dept",
        ),
    ]
