# Generated by Django 4.2.6 on 2023-10-29 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_team_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
    ]
