# Generated by Django 4.2.6 on 2023-10-30 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("team", "0003_remove_team_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="access_group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
            ),
        ),
    ]
