# Generated by Django 4.2.6 on 2023-11-01 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_alter_organization_subsidiaries"),
        ("team", "0004_team_access_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.organization",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="parent_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent",
                to="team.team",
            ),
        ),
    ]
