# Generated by Django 4.2.6 on 2023-11-01 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0005_team_organization_team_parent_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="parent_team",
        ),
    ]
