# Generated by Django 4.2.6 on 2023-11-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0003_department"),
        ("team", "0006_remove_team_parent_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="organization",
        ),
        migrations.AddField(
            model_name="team",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.department",
            ),
        ),
    ]
