# Generated by Django 4.2.6 on 2023-11-01 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0007_remove_team_organization_team_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="department",
        ),
    ]
