# Generated by Django 4.2.6 on 2023-11-01 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0004_rename_org_department_dept"),
        ("team", "0009_team_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team",
                to="department.department",
            ),
        ),
    ]
