# Generated by Django 4.2.7 on 2023-12-07 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0010_alter_team_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="team",
        ),
    ]
