# Generated by Django 4.2.4 on 2023-10-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notetag",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
