# Generated by Django 4.2.4 on 2023-10-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_alter_notetag_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="notetag",
            name="note_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
