# Generated by Django 4.2.4 on 2023-10-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0004_remove_notetag_note_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="notetag",
            name="note_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
