# Generated by Django 4.2.4 on 2023-10-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_notetag_note_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notetag',
            name='note_count',
        ),
    ]
