# Generated by Django 4.2.6 on 2023-11-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0006_remove_notetag_note_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="notetag",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
