# Generated by Django 4.2.6 on 2023-11-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0008_notetag_created_at_notetag_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="attachments",
            field=models.FileField(blank=True, null=True, upload_to="attachments"),
        ),
    ]
