# Generated by Django 4.2.6 on 2023-11-09 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0009_note_attachments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="attachments",
            new_name="attachment",
        ),
    ]
