# Generated by Django 4.2.6 on 2023-11-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0011_alter_note_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(blank=True, to="notes.notetag"),
        ),
    ]
