# Generated by Django 4.2.4 on 2023-10-24 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='meetest',
        ),
    ]
