# Generated by Django 4.2.6 on 2023-11-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetings",
            name="report",
            field=models.TextField(blank=True, null=True),
        ),
    ]
