# Generated by Django 4.2.7 on 2023-12-07 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0004_meetings_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetings",
            name="meeting",
        ),
    ]
